server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/

# Actuator
management:
  server:
    port: 9002
  endpoints:
    web:
      exposure:
        include: "*"  #监控所有的接口
