server:
  port: 8089

spring:
  # datasource conf
  datasource:
    hikari:
      pool-name: HikariCP
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/word?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: root
      password: 123456
      connection-test-query: SELECT 1
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      connection-timeout: 30000

# redis conf
#  redis:
#    host: localhost
#    port: 6379
#    database: 1
#    jedis:
#      pool:
#        max-idle: 500
#        max-wait: -1ms
#        max-active: 8
