# 设置当前环境
spring:
  profiles:
    active: dev

server:
  port: 8081

# Actuator
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"  #监控所有的接口

# Eureka
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/